FROM node:lts-alpine as base

ENV NODE_ENV=development

WORKDIR /src

# Build
FROM base as build

COPY --link package.json .

RUN npm install

# Run
FROM base

COPY --from=build /src/node_modules /src/node_modules

EXPOSE 5173
CMD [ "npm", "run", "dev" ]
